"""criando tabelas iniciais

Revision ID: f5af7a987e48
Revises: 
Create Date: 2025-12-09 15:37:10.559154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5af7a987e48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id_venda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('produto', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_venda', sa.DATE(), nullable=True),
    sa.Column('preco', mysql.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
